### PR TITLE
Sublime Text added

### PR DESCRIPTION
**Pull request by rsaporta**

### CODE REVIEW

**Comment by qinwf** [comment]
Thanks! 

Would you please create anohter pull request with a shorter description. Maybe 
`R-Box is an add-on package for Sublime Text 2/3. ` is sufficient.

**Comment by rsaporta** [comment]
Done.

**Comment by qinwf** [comment]
Anohter pull request is better. Merging this branch will make master branch have two more commits.

**Comment by qinwf** [comment]
`Mac, Windows, Linux` can also be removed, since it is a cross-platform and well-known text editor.

**Pull request closed without merging**
