### PR TITLE
Add httr - Web Technologies and Services section

### PR DESCRIPTION
**Pull request by zero323**

### CODE REVIEW

**Comment by qinwf** [comment]
User-friendly or User friendly?

**Comment by zero323** [comment]
Good point. [Cambridge dictionary says](http://dictionary.cambridge.org/dictionary/british/user-friendly) user-friendly. Corrected.

**Comment by qinwf** [comment]
Maybe a new pull request to be cleaner?

**Comment by zero323** [comment]
Moved to #52

**Pull request closed without merging**
