### PR TITLE
Add MOOCs section. 

### PR DESCRIPTION
**Pull request by zero323**

### CODE REVIEW

**Comment by qinwf** [comment]
Thanks! I suggest that we can keep It simpler, and provide limited but sufficient choices. 
Maybe sublinks can be simplified. 

I did not take any of these courses, and I do not know about their quality, and I hope to get some of opinion on these. If all of them are really good, we can surely add it.

Here is a example.
## MOOCs
*Massive open online courses.*
* [The Analytics Edge](https://www.edx.org/course/analytics-edge-mitx-15-071x-0) - Hands-on introduction to data analysis with R from MITx.
* [Johns Hopkins University Data Science specialization](https://www.coursera.org/specialization/jhudatascience/1) - 9 courses including: Introduction to R, literate analysis tools, Shiny and some more.
* [HarvardX Biomedical Data Science](http://simplystatistics.org/2014/11/25/harvardx-biomedical-data-science-open-online-training-curriculum-launches-on-january-19/) - Introduction to R for the Life Sciences.
* [Data Analysis with R](https://www.udacity.com/course/data-analysis-with-r--ud651) - Exploratory Data Analysis with R from Udacity/Facebook. 
* [Bioconductor for Genomic Data Science](https://www.coursera.org/course/genbioconductor) - Introduction to the Bioconductor project from Coursera/JHU.

**Comment by zero323** [comment]
Fine by me. Truth be told I wasn't completely sure about the sublist idea. 

Regrading quality it is a tricky question. I didn't try Data Analysis with R and Bioconductor for Genomic Data Science is an upcoming course so I cannot say anything about these two. Remaining courses are actually pretty good for someone  who wants to learn how to use R as an interactive data analysis tool and to get some basics of the statistics and machine learning on the way. Each (I consider both HarvardX and DS Specialization as a whole) has its own specifics so it is not easy to recommend one over another. 

This was a good part. Bad part is these courses have been designed by people who are clearly not the software developers. It means all kinds of ugly stuff which rots your brain and hurts your eyes. For someone who is looking for a way to learn how to use R as programming language it is most likely a waste of time. Is it a problem?  I am not sure. It is a common issue when it comes to R resources but as far as I can tell most of the time no one cares.

**Comment by qinwf** [comment]
All rigth! Maybe we can add `Data Analysis with R` and `Bioconductor for Genomic Data Science` to this later. Would you mind to create another pull request? 

I found [Advanced R](http://adv-r.had.co.nz/) to be a good resource to learn R as programming language.

**Comment by zero323** [comment]
Yep, Advanced R is really good. I really enjoyed [Advanced Data Analysis Software Development with R](https://courses.ipipan.edu.pl/simple.php?page=syllabus018.html) by @gagolews but with all the required paperwork it is hard to call it an open course. 

Sure, I'll create another pull request. Flat structure with three positions (The Analytics Edge,
Johns Hopkins University Data Science specialization and HarvardX Biomedical Data Science), right?

**Pull request closed without merging**
