### PR TITLE
Add bigmemory.

### PR DESCRIPTION
**Pull request by zero323**

### CODE REVIEW

**Comment by zero323** [comment]
There is probably a better way to add this, but I think that `bigmemory` alone is better choice than keeping separate packages from the `big*` family in the Machine Learning section.

**Comment by qinwf** [comment]
It have not been updated since 2013-11-18. And it is not supported for Windows binaries on CRAN for now. Maybe we can merge this later.

**Comment by qinwf** [comment]
bigmemory is now on CRAN, and supports Windows, Mac and Linux. This branch has conflicts. Could you please create another pull request and I can merge it.

Thanks.

**Comment by zero323** [comment]
@qinwf  Done.

**Comment by qinwf** [comment]
## MOOCs
*Massive open online courses.*

* [The Analytics Edge](https://www.edx.org/course/analytics-edge-mitx-15-071x-0) - Hands-on introduction to data analysis with R from MITx.
* [Johns Hopkins University Data Science Specialization](https://www.coursera.org/specialization/jhudatascience/1) - 9 courses including: Introduction to R, literate analysis tools, Shiny and some more.
* [HarvardX Biomedical Data Science](http://simplystatistics.org/2014/11/25/harvardx-biomedical-data-science-open-online-training-curriculum-launches-on-january-19/) - Introduction to R for the Life Sciences.
* [Explore Statistics with R](https://www.edx.org/course/explore-statistics-r-kix-kiexplorx-0) - Covers introduction, data handling and statistical analysis in R.

## MOOCs
*Massive open online courses.*
* [The Analytics Edge](https://www.edx.org/course/analytics-edge-mitx-15-071x-0) - Hands-on introduction to data analysis with R from MITx.
* [Johns Hopkins University Data Science specialization](https://www.coursera.org/specialization/jhudatascience/1) - 9 courses including:
    - [R Programming](https://www.coursera.org/course/rprog) - Quick introduction to R programming.
    - [Reproducible Research](https://www.coursera.org/course/repdata) - Introduction to literate analysis tools.
    - [Developing Data Products](https://www.coursera.org/course/devdataprod) - Introduction to Shiny.
* [HarvardX Biomedical Data Science](http://simplystatistics.org/2014/11/25/harvardx-biomedical-data-science-open-online-training-curriculum-launches-on-january-19/) - Introduction to R for the Life Sciences. 8 courses including:
    - [Statistics and R for the Life Sciences](https://www.edx.org/course/statistics-r-life-sciences-harvardx-ph525-1x) - Basics of statistical inference with examples in R.
    - [Advanced Statistics for the Life Sciences](https://www.edx.org/course/advanced-statistics-life-sciences-harvardx-ph525-3x) - Analysis of the complex genomics datasets.
    - [Introduction to Bioconductor](https://www.edx.org/course/introduction-bioconductor-harvardx-ph525-4x) - Description of the basic Bioconductor packages. 
* [Data Analysis with R](https://www.udacity.com/course/data-analysis-with-r--ud651) - Exploratory Data Analysis with R from Udacity/Facebook. 
* [Bioconductor for Genomic Data Science](https://www.coursera.org/course/genbioconductor) - Introduction to the Bioconductor project from Coursera/JHU.

**Comment by qinwf** [comment]
Could you please create a new pull request or force push?

**Pull request closed without merging**
