### PR TITLE
Update Websites and Books section

### PR DESCRIPTION
**Pull request by navdeep-G**

### CODE REVIEW

**Comment by qinwf** [comment]
Thanks. 

`The R Inferno` is a great book. The link to the blog post is not suitable for the Websites section. 

And could you please change your editor line ending setting to avoid `454 additions and 452 deletions`.

Please force push or create another pull request to keep one pull request with one commit.

**Comment by qinwf** [comment]
Commit message should be more informative. you should provide information about the book you add to this list.

**Comment by navdeep-G** [comment]
Hi

I am not sure what is going on with the additions or deletions. I'm looking into it.

Thanks

**Comment by navdeep-G** [comment]
I will end this PR and try another.

**Pull request closed without merging**
