### PR TITLE
added few books, a website and a MOOC

### PR DESCRIPTION
**Pull request by ujjwalkarn**
Please review

### CODE REVIEW

**Comment by qinwf** [comment]
The edX course is not opened on that link. i suggest this link https://www.edx.org/course/explore-statistics-r-kix-kiexplorx-0

**Comment by qinwf** [comment]
`The R Guide` now contains in the [Free Books link]( https://github.com/qinwf/awesome-R#books)

**Comment by qinwf** [comment]
`R for SAS and SPSS Users` a newer link http://r4stats.com/books/free-version/

**Comment by ujjwalkarn** [comment]
Thanks for the suggestions Qin! I have made the changes. Please let me know if everything looks fine now.

**Comment by qinwf** [comment]
You can reset this branch to one commit, or create a new pull request.

**Comment by ujjwalkarn** [comment]
I have created a new pull request. Closing this one.

**Pull request closed without merging**
