### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vnijs**
FYI This is a package that I developed. I would also recommend adding <https://github.com/yindeng/shinyData> and <http://www.intro-stats.com/>

### CODE REVIEW

**Comment by qinwf** [comment]
Thanks! 

I think it might be better to add `Radiant` to `Web Technologies and Services` section. If there will be more shiny based projects, we can add a `Shiny Apps` section In the future, .

And a clearer commit message will make the history look better too. "Update README.md" may be insufficient.

You can create another pull request to make these changes.

**Comment by vnijs** [comment]
Thanks for your comments @qinwf. I can definitely  provide a better commit message :) I am not sure about adding radiant to the Web technologies list however. Radiant (and the other two apps I mentioned) are not 'like' Shiny but built 'in' Shiny. There are galleries for shiny apps (e.g., http://www.rstudio.com/products/shiny/shiny-user-showcase/) and I'm not sure such a general category would add much value to your list. I see Radiant as a GUI for statistical analysis (specifically business analytics) with some similarities to Deducer and Rcmdr. If you are not comfortable with that classification please let me know. If you are ok with that classification I will create another pull request. Your list, your call.

**Comment by qinwf** [comment]
Yeah, you can create that pull request. I have been `watching` it for a while :smile: .

Radiant is really convenient. I hope that more features can come in the future, and make it work as an efficient [IDE](http://en.wikipedia.org/wiki/Integrated_development_environment).

**Comment by vnijs** [comment]
Thanks Qin. What features would you (most) like to see added?

Vincent

**Pull request closed without merging**
